### PR TITLE
Shell scripts for setting up new aurad node and systemd monitoring service.

### PR DESCRIPTION
**Pull request by kokleong98**
Shell scripts for setting up new aurad node and systemd monitoring service.

Simple guide in my original github repository.
https://github.com/kokleong98/aura-setup

### CODE REVIEW

**Comment by yennieb** [comment]
Great stuff @kokleong98 I'm going to try this out in more detail but seems to address a lot of points at once around maintaining uptime!

**Comment by kokleong98** [comment]
> Great stuff @kokleong98 I'm going to try this out in more detail but seems to address a lot of points at once around maintaining uptime!

I could make it better, if you have more suggestion. I'm supporting infura.io option in my original repo, rougly tested it.

**Comment by kokleong98** [comment]
Just restructure the code and added 2 minor features.
- Aurad block sync wait at aura.service start-up.
- Aurad software update email notification. (Untested)

**Comment by kokleong98** [comment]
Tested monitoring service able to bring fresh setup droplet from zero sync to fully sync by restarting aurad container when it sync status stuck in offline.

**Comment by yennieb** [comment]
Closing in favor of updated PR

**Pull request closed without merging**
